create table tab_person (
                           col_id int GENERATED BY DEFAULT AS IDENTITY,
                           col_name text,
                           col_date timestamp,
                           PRIMARY KEY (col_id)
);

insert into tab_person (col_name, col_date) values ('Achmed', '2019-10-09T23:11:00');
insert into tab_person (col_name, col_date) values ('Rudolf', '2010-10-09T23:11:00');
